<?php

namespace Database\Factories;

use App\Models\HealthcareProvider;
use App\Models\Member;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\HealthClaim>
 */
class HealthClaimFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $claimType = fake()->randomElement(['outpatient', 'inpatient', 'surgery', 'maternity']);
        $billedAmount = fake()->randomFloat(2, 1000, 50000);
        $coveragePercent = 90.00;
        $coveredAmount = $billedAmount * ($coveragePercent / 100);
        $copayAmount = $billedAmount - $coveredAmount;

        return [
            'member_id' => Member::factory(),
            'healthcare_provider_id' => HealthcareProvider::factory(),
            'claim_type' => $claimType,
            'billed_amount' => $billedAmount,
            'coverage_percent' => $coveragePercent,
            'covered_amount' => $coveredAmount,
            'copay_amount' => $copayAmount,
            'claim_date' => fake()->dateTimeBetween('-6 months', 'now'),
            'status' => fake()->randomElement(['submitted', 'approved', 'rejected', 'paid']),
            'approved_by' => User::factory(),
            'paid_by' => User::factory(),
            'paid_date' => fake()->optional(0.3)->dateTimeBetween('-3 months', 'now'),
            'remarks' => fake()->optional(0.4)->sentence(),
            'claim_number' => null, // Will be generated by model
        ];
    }

    /**
     * Indicate that the claim is submitted.
     */
    public function submitted(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'submitted',
            'approved_by' => null,
            'paid_by' => null,
            'paid_date' => null,
        ]);
    }

    /**
     * Indicate that the claim is approved.
     */
    public function approved(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'approved',
            'paid_by' => null,
            'paid_date' => null,
        ]);
    }

    /**
     * Indicate that the claim is paid.
     */
    public function paid(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'paid',
            'paid_date' => fake()->dateTimeBetween('-1 month', 'now'),
        ]);
    }

    /**
     * Indicate that the claim is rejected.
     */
    public function rejected(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'rejected',
            'paid_by' => null,
            'paid_date' => null,
        ]);
    }

    /**
     * Indicate that the claim is for outpatient services.
     */
    public function outpatient(): static
    {
        return $this->state(fn (array $attributes) => [
            'claim_type' => 'outpatient',
            'billed_amount' => fake()->randomFloat(2, 1000, 10000),
        ]);
    }

    /**
     * Indicate that the claim is for inpatient services.
     */
    public function inpatient(): static
    {
        return $this->state(fn (array $attributes) => [
            'claim_type' => 'inpatient',
            'billed_amount' => fake()->randomFloat(2, 15000, 50000),
        ]);
    }

    /**
     * Indicate that the claim is for surgery.
     */
    public function surgery(): static
    {
        return $this->state(fn (array $attributes) => [
            'claim_type' => 'surgery',
            'billed_amount' => fake()->randomFloat(2, 20000, 100000),
        ]);
    }

    /**
     * Indicate that the claim is for maternity services.
     */
    public function maternity(): static
    {
        return $this->state(fn (array $attributes) => [
            'claim_type' => 'maternity',
            'billed_amount' => fake()->randomFloat(2, 10000, 30000),
        ]);
    }

    /**
     * Indicate that the claim is recent.
     */
    public function recent(): static
    {
        return $this->state(fn (array $attributes) => [
            'claim_date' => fake()->dateTimeBetween('-1 month', 'now'),
        ]);
    }

    /**
     * Indicate that the claim is old.
     */
    public function old(): static
    {
        return $this->state(fn (array $attributes) => [
            'claim_date' => fake()->dateTimeBetween('-6 months', '-3 months'),
        ]);
    }
}
